spring:
  config:
    activate:
      on-profile: default

server:
  port: 5000

---

spring:
  config:
    activate:
      on-profile: prod

server:
  port: 3000

---

spring:
  config:
    activate:
      on-profile: test

server:
  port: 4000